spring:
  datasource:
    url: jdbc:mysql://askme-test.verda-askme.jp2-dev.db.line-apps-dev.com:20306/test
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: askme_test
    password: askme_test
  jpa:
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
#  h2:
#    console:
#      enabled: true # http://localhost:8080/h2-console 로 접속 가능.
